/* Generates supabase/migrations/0004_seed_catalog.sql from the mock catalog,
 * so live orders can reference real product_variants rows (RLS + FKs work).
 * Run: npx tsx scripts/generate-catalog-seed.mts
 */
import { createHash } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PRODUCTS, SELLERS, CATEGORIES } from "../lib/mock";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "supabase", "migrations");
mkdirSync(outDir, { recursive: true });

// Deterministic UUID v4-like value from a stable string (idempotent across runs).
function dUuid(seed: string) {
  const hex = createHash("md5").update(seed).digest("hex");
  return (
    hex.slice(0, 8) +
    "-" +
    hex.slice(8, 12) +
    "-4" +
    hex.slice(13, 16) +
    "-" +
    "89ab".charAt(Number.parseInt(hex, 16) % 4) +
    hex.slice(17, 20) +
    "-" +
    hex.slice(20, 32)
  );
}

const lines: string[] = [];
lines.push("-- Generated by scripts/generate-catalog-seed.mts — do not edit by hand.");
lines.push("-- Mirrors the mock catalog (lib/mock.ts) into the live schema so order_items");
lines.push("-- can reference product_variants with valid FKs and RLS-visible records.");
lines.push("");

lines.push("-- Categories");
lines.push("insert into public.categories (id, name_fr, name_en, slug, position) values");
const catSql = CATEGORIES.map((c, i) => {
  const name = `${c.label.charAt(0)}${c.label.slice(1).toLowerCase()}`;
  return `  ('${dUuid(`category:${c.slug}`)}', '${name}', '${name}', '${c.slug}', ${i})`;
});
lines.push(catSql.join(",\n") + "\non conflict (slug) do nothing;");
lines.push("");

lines.push("-- Vendors (mock sellers)");
lines.push(
  "insert into public.vendors (id, owner_id, name, slug, description, wilaya_id, commune_id, status, commission_rate) values"
);
const vendorSql = SELLERS.map(
  (s) =>
    `  ('${dUuid(`vendor:${s.id}`)}', null, '${s.name.replace(/'/g, "''")}', '${s.id}', '', null, null, 'active', 0.10)`
);
lines.push(vendorSql.join(",\n") + "\non conflict (slug) do nothing;");
lines.push("");

lines.push("-- Products");
const catSlugByLabel: Record<string, string> = {};
for (const c of CATEGORIES) catSlugByLabel[c.label] = c.slug;
const productSql = PRODUCTS.map(
  (p) =>
    `  ('${dUuid(`product:${p.id}`)}', (select id from public.categories where slug = '${
      catSlugByLabel[p.category]
    }'), (select id from public.vendors where slug = '${p.sellerId}'), '${p.name.replace(
      /'/g,
      "''"
    )}', '${p.id}', '', ${p.price}, 'DZD', 'active')`
);
lines.push(
  "insert into public.products (id, category_id, vendor_id, name, slug, description, base_price, currency, status) values"
);
lines.push(productSql.join(",\n") + "\non conflict (slug) do nothing;");
lines.push("");

lines.push("-- Product variants (one per size)");
const variantSql: string[] = [];
for (const p of PRODUCTS) {
  for (const size of p.sizes) {
    const sku = `${p.id}-${size.replace(/\s+/g, "").toUpperCase()}`;
    variantSql.push(
      `  ('${dUuid(`variant:${p.id}:${size}`)}', (select id from public.products where slug = '${
        p.id
      }'), '${size.replace(/'/g, "''")}', null, '${sku}', ${p.price}, 8)`
    );
  }
}
lines.push(
  "insert into public.product_variants (id, product_id, size, color, sku, price_override, stock_quantity) values"
);
lines.push(variantSql.join(",\n") + "\non conflict (sku) do nothing;");
lines.push("");

lines.push("-- Product images (one row per angle)");
const imageSql: string[] = [];
for (const p of PRODUCTS) {
  p.imageUrls.forEach((url, i) => {
    imageSql.push(
      `  ('${dUuid(`image:${p.id}:${i}`)}', (select id from public.products where slug = '${
        p.id
      }'), null, '${url.replace(/'/g, "''")}', ${i})`
    );
  });
}
lines.push("insert into public.product_images (id, product_id, variant_id, url, position) values");
lines.push(imageSql.join(",\n") + "\non conflict (id) do nothing;");
lines.push("");

const out = join(outDir, "0004_seed_catalog.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`Wrote ${out} (${lines.length} lines).`);