-- =============================================================================
-- Abyss — 0015: public catalog RPCs (real catalog checkout)
--
-- The storefront reads the live catalog through these SECURITY DEFINER RPCs
-- (tables are locked since 0009). Called server-side with the service role,
-- same pattern as the vendor RPCs — no anon/authenticated grants needed.
--
--   • catalog_products  — active products of active vendors (paged, filterable)
--   • catalog_product   — one product by slug, with variants + images
--
-- NOTE: vendor-created products carry category_id = null until category
-- assignment lands in the desk — they surface under "all" meanwhile.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. catalog_products — grid payload.
-- ---------------------------------------------------------------------------
